// Root Layout，用來放所有 route 都會固定出現的 components、設定 metadata，以及修改 initial HTML 的內容
// 會被當作 app 路由下的 layout，/app 底下的頁面元件就會以 children props 的方式傳入 RootLayoutt 中

import "./globals.css";

export const metadata = {
  title: "JPetStore Demo",
  description: "Generated by create next app",
};

// children: React.ReactNode
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}

// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "JPetStore Demo",
//   description: "Generated by create next app",
// };

// // children: React.ReactNode
// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
