services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jamstack_backend_container
    ports:
      - "8080:8080"
    networks:
      - jamstack_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_DOMAIN: http://localhost:8080
    container_name: jamstack_frontend_container
    ports:
      - "3000:3000"
    networks:
      - jamstack_network
    depends_on:
      - backend

networks:
  jamstack_network:
